version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
      - /client/node_modules
      - .:/client
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - /client/node_modules
      - .:/client
    command: ["npm","run","start"]